[features]
seeds = false
skip-lint = false
[programs.localnet]
twitter_app = "HDz4EuZFyrZ1WDXht5NSm2S9N2MhPj1dCzAA5zjk5kfk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/kos/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
